Server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: '6396'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
        dialect: org.hibernate.dialect.PostgreSQL81Dialect


